vxlan: rollback changes on config failure
If iface_vxlan_reconfig fails before returning, currently there are some
bits of configuration that remain, namely the hash table may have been
modified but if the nexthop or mac address configuration fails, the hash
table isn't reverted to its previous state.

This can cause obscure errors when redoing configuration, for example:

 grout# interface add vxlan vni100 vni 100 local 172.16.0.1 domain br0
 error: command failed: Network is unreachable (ENETUNREACH)

 grout# address add 172.16.0.1/24 iface p0

 grout# interface add vxlan vni100 vni 100 local 172.16.0.1 domain br0
 error: command failed: Address already in use (EADDRINUSE)

Record every field that was configured incrementally and undo every bit
on error.

Signed-off-by: Robin Jarry <rjarry@redhat.com>
Reviewed-by: David Marchand <david.marchand@redhat.com>