nexthop: allow deleting by key instead of ID
Change GR_NH_DEL to accept a full struct gr_nexthop instead of just an
ID. The handler uses nexthop_lookup() which first tries the ID if
specified or falls back to the type-specific key-based lookup (e.g.
vrf+addr for L3). This will allow the FRR plugin to delete remote
nexthops installed from EVPN neighbor entries without tracking their
auto-allocated IDs.

The nexthop type ids must be changed to avoid an error when deleting
a nexthop from its ID which has already been deleted indirectly:

ZEBRA: GROUT: grout_del_nexthop: nh_id 16

ERROR: AddressSanitizer: heap-buffer-overflow, READ of size 1
    #0 in l3_lookup ../modules/infra/control/l3_nexthop.c:112
    #1 in nexthop_lookup ../modules/infra/control/nexthop.c:306
    #2 in nh_del ../modules/infra/api/nexthop.c:56
    #3 in read_cb ../main/api.c:315

ZEBRA: GROUT: grout_client_send_recv: ERROR: GR_NH_DEL: Connection reset by peer

Indeed, since nh->type=0 is both the unset value and GR_NH_T_L3, the
nexthop_lookup() code calls l3_lookup() with nh->info pointing to
outside the API message buffer.

The only reliable to guard against this is to make GR_NH_T_L3 != 0.
Shift all enum values up by one and adjust code accordingly.

Signed-off-by: Robin Jarry <rjarry@redhat.com>
Reviewed-by: Christophe Fontaine <cfontain@redhat.com>