ci: allow dpdk 25.11 head test to fail
A recent backport to the 25.11 staging branch cause build errors in
ethdev:

../subprojects/dpdk-25.11-head/lib/ethdev/ethdev_driver.c: In function 'rte_eth_dev_allocate':
../subprojects/dpdk-25.11-head/lib/ethdev/ethdev_driver.c:138:9: error: implicit declaration of function 'rte_thread_mutex_init_shared' [-Wimplicit-function-declaration]
  138 |         rte_thread_mutex_init_shared(&eth_dev->data->flow_ops_mutex);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Allow this test to fail until a proper fix has been applied upstream.
This test (along with the frr master one) is meant as a canary build
anyway. It allows us to detect issues *before* versions are released and
it gives us a chance to react in advance.

Link: https://github.com/DPDK/dpdk-stable/commit/3586d8ad0ebb
Signed-off-by: Robin Jarry <rjarry@redhat.com>