cli: support partial arguments
libecoli now has functions to expand strings in a vector using
non-ambiguous command completion.

Use ec_node_sh_lex_expand() instead of ec_node_sh_lex() which takes care
of this transparently.

When validating a command, call ec_complete_strvec_expand() explicitly
so that we can display useful error messages to the user, e.g.:

	grout# i a porc x devargs net_null
	* interface add porc x devargs net_null
	*               ^
	error: invalid arguments
	expected: ipip, port, vlan

Signed-off-by: Robin Jarry <rjarry@redhat.com>