stats: fix error when dumping stats without any ports configured
When dumping software stats and no ports are configured, no workers are
reporting any stats and we get an error:

	grout# stats show software
	error: command failed: No such device

Do not return an error when asking to dump all CPUs.

Fixes: 7c94f16c572e ("stats: allow filtering by cpu id")
Signed-off-by: Robin Jarry <rjarry@redhat.com>