infra: fix type conversion in trace
ip6->proto was converted from uint8_t to int to be displayed.
error: format specifies type 'unsigned char' but the argument has type 'int'

Signed-off-by: Christophe Fontaine <cfontain@redhat.com>