trace: fix error when count is not specified
When running trace show without specifying the count the CLI returns an
error:

  grout# trace show
  error: command failed: No such file or directory (ENOENT)

The count argument is optional, do not fail if it was not specified.

Fixes: 0edd9956e7cc ("trace: return packets by batches")
Signed-off-by: Robin Jarry <rjarry@redhat.com>
Reviewed-by: Christophe Fontaine <cfontain@redhat.com>