dpaa2: do not close devices
The dpaa2 devices do not support close/re-open with the current DPDK.
Let's work around this limitation for the time being.

From the design of the DPDK's fslmc bus, it seems to be the only
option for the time being.

Fix:
 grout# add interface port dpni.2 devargs fslmc:dpni.2 up mode l3
 Created interface 1
 grout# del interface dpni.2
 grout# add interface port dpni.2 devargs fslmc:dpni.2 up mode l3
 error: command failed: Identifier removed

Fixes: 9ca93361aea1 ("port: allow attaching already probed device")
Signed-off-by: Vincent Jardin <vjardin@free.fr>