github: force fetch tags again
Attempt fixing the following error:

~$ git fetch origin 'refs/tags/v*:refs/tags/v*'
From https://github.com/DPDK/grout
 ! [rejected]        v0.8.1     -> v0.8.1  (would clobber existing tag)
Error: Process completed with exit code 1.

Fixes: eef6c554f27d ("github: force fetch tags")
Signed-off-by: Robin Jarry <robin@jarry.cc>