treewide: fix compilation with clang
clang does not support gcov. It has its own internal coverage system.
Running instrumented binaries requires specific actions which are less
practical and would require too many changes. Disable coverage when
building with clang.

Also, clang 16 does not have -Wno-format-truncation. Move it to the
optional C arguments.

Also, fix the following error reported by clang:

../modules/l4/l4_input_local.c:31:60: error: format specifies type
       'unsigned char' but the argument has type 'rte_be16_t' (aka
       'unsigned short') [-Werror,-Wformat]
 31 |  ABORT("next node already registered for udp port=%hhu", port);
    |                                                   ~~~~   ^~~~
    |                                                   %hu

More than a type error, the port value is in big-endian. Change it back
to host order and fix the printf specifiers to accommodate a 16 bit
unsigned integer.

Fixes: 1d6f86af1bd1 ("l4: add udp port handler")
Signed-off-by: Robin Jarry <robin@jarry.cc>