ip6: fix crash in iface_ra_show
Fix the following crash when running `show ip6 router-advert`:

ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7f4fb3aba5b8
at pc 0x000000518eeb bp 0x7fff0de9b2b0 sp 0x7fff0de9b2a8

READ of size 8 at 0x7f4fb3aba5b8 thread T0
  #0 0x518eea in gr_vec_len ../main/gr_vec.h:35
  #1 0x5197f5 in iface_ra_show ../modules/ip6/control/router_advert.c:90
  #2 0x4050e3 in read_cb ../main/api.c:287
  ...
  #5 0x409566 in main ../main/main.c:210

The hoplist structure contains a gr_vec of nexthop objects.

Fixes: 8ed8b9d594c9 ("ip6: router advertisement configuration")
Signed-off-by: Robin Jarry <robin@jarry.cc>