mempool: fix build error on aarch64
Fix the following error when building on aarch64:

../modules/infra/control/mempool.c: In function ‘gr_pktmbuf_pool_get’:
../modules/infra/control/mempool.c:87:17: error: implicit declaration
                of function ‘qsort’ [-Wimplicit-function-declaration]
   87 |                 qsort(mt, MAX_MEMPOOL_PER_NUMA, sizeof(*mt), mt_sort);
      |                 ^~~~~

Add the missing include of stdlib.h

Fixes: 189ae9d7a5b9 ("infra: add wrapper to create mempools")
Signed-off-by: Robin Jarry <robin@jarry.cc>