infra: enable deletion of iface nexthops by dropping GR_NH_F_LINK check
Example:
  grout# add nexthop id 123 iface gr-loop1
  grout# del nexthop 123
  error: command failed: Device or resource busy

Because GR_NH_F_LOCAL is already set interface‐address nexthops, the
GR_NH_F_LINK test in nh_del() is not useful. By removing this one, iface
nexthop can be deleted.

Signed-off-by: Maxime Leroy <maxime@leroys.fr>