bond: fix init with lacp mode
Since commit ec4cbdc7f18f ("port: always enable allmulti and simplify
MAC filtering"), filtering multicast addresses is no longer necessary.
Allmulti is always enabled. Calling iface_add_eth_addr() with
a non-unicast address returns an error.

The lacp test fails when doing so:

+ grcli interface add bond bond0 mode lacp member p0 member p1 member p2
DEBUG: GROUT: bond_init_new_members: adding p0 to bond bond0
ERR: GROUT: bond_init_new_members: iface_add_eth_addr(lacp): Invalid argument (22)
error: command failed: Invalid argument (EINVAL)

Do not add the LACP multicast address to the port filters.

Fixes: f2b09727b0b8 ("bond: add lacp support")
Signed-off-by: Robin Jarry <rjarry@redhat.com>
Reviewed-by: Anthony Harivel <aharivel@redhat.com>