github: fix ai review action (fix)
Remove cache argument to fix the following error:

Error: No file in /home/runner/work/grout/grout matched to
[**/requirements.txt or **/pyproject.toml], make sure you have checked
out the target repository

Fixes: 4cd3417c77c1 ("github: fix ai review action")
Signed-off-by: Robin Jarry <robin@jarry.cc>