main: allow indirect linking with libsystemd.so
Avoid the following error when linking to DPDK dynamic libraries which
are indirectly linked to libsystemd:

/usr/bin/x86_64-linux-gnu-ld.bfd: /usr/lib/x86_64-linux-gnu/libsystemd.a(src_libsystemd_sd-daemon_sd-daemon.c.o): in function `sd_notifyf':
(.text+0x2030): multiple definition of `sd_notifyf'; grout.p/main_sd_notify.c.o:./obj-x86_64-linux-gnu/../main/sd_notify.c:36: first defined here

Rename our symbol to avoid any conflict. Add a format(printf) attribute
for good measure.

Signed-off-by: Robin Jarry <rjarry@redhat.com>
Reviewed-by: Maxime Leroy <maxime@leroys.fr>