ctlplane: skip vrf master config for bridged interfaces
When an interface is in a bridge, its vrf_id is 0 (unset). However,
grout tries to enslave its control plane TAP representor to a l3mdev
regardless of the value of vrf_id, which leads to this error in logs:

  ERROR: cp_set_vrf_master: no VRF iface for id 0 on vni210

This is not affecting the packet flow and is only cosmetic but let's not
try to configure this unless the interface is in VRF mode.

Fixes: 31073d12f652 ("infra: enslave control-plane TAPs to VRF master")
Signed-off-by: Robin Jarry <rjarry@redhat.com>
Reviewed-by: David Marchand <david.marchand@redhat.com>